# official documentation: https://prometheus.io/docs/alerting/latest/configuration/

route:
  # default receiver
  receiver: signal

receivers:
- name: signal
  webhook_configs:
  # depends on your dns setup, could also be an ip address
  - url: http://signal-receiver:9709/alert
