name: CI
on:
- push
- pull_request
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Install golang
      uses: actions/setup-go@v2
    - name: Fetch source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Lint
      run: go vet ./...
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Install golang
      uses: actions/setup-go@v2
    - name: Fetch source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Test
      run: go test -race ./...
  publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Fetch source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: docker build -t dadevel/alertmanager-signal-receiver .
    - name: Test
      run: docker run --rm --entrypoint sh dadevel/alertmanager-signal-receiver -c 'signal-cli --version'
