name: Publishing
on:
  push:
    branches:
    - main
  schedule:
  # weekly rebuilds
  - cron: 0 3 * * 0
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Fetch source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build & push image
      run: |
        VERSION="$(git show-ref | cut -d ' ' -f 2- | grep ^refs/tags/ | grep -Eo '[0-9.]+$' | sort -V | tail -n 1)"
        docker login --username dadevel --password-stdin ghcr.io <<< "$GITHUB_TOKEN"
        trap 'docker logout' EXIT
        docker buildx build \
          --platform linux/amd64 \
          --label org.opencontainers.image.title="$IMAGE_TITLE" \
          --label org.opencontainers.image.author="$IMAGE_AUTHOR" \
          --label org.opencontainers.image.source="$IMAGE_SOURCE" \
          --label org.opencontainers.image.version="$VERSION" \
          --tag ghcr.io/dadevel/alertmanager-signal-receiver:latest \
          --tag ghcr.io/dadevel/alertmanager-signal-receiver:"$VERSION" \
          --push \
          .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_CLI_EXPERIMENTAL: enabled
        BUILDX_NO_DEFAULT_LOAD: 'false'
        IMAGE_TITLE: Alertmanager Signal Receiver
        IMAGE_AUTHOR: dadevel
        IMAGE_SOURCE: https://github.com/dadevel/alertmanager-signal-receiver
